name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Testing 
    - name: Print Docker Secrets
      run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"

    # Step 2: Log in to DockerHub (or any Docker registry you're using)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Store this in GitHub Secrets
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  # Store this in GitHub Secrets

    # Step 3: Set up Docker Buildx (for multi-platform builds if needed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

     # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest .

    # Step 5: Push Docker image
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest

    # Step 6: Testing 
    - name: Print Docker Secrets
      run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"